name: snickers_chat_v4
description: "SnickersChatv4 - Olağanüstü Şık Android Flutter Sohbet Uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # State Management
  provider: ^6.1.1

  # Animations
  animations: ^2.0.8
  flutter_animate: ^4.5.0

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0

  # Utilities
  intl: ^0.19.0
  timeago: ^3.6.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
